initialize BaseExtraList flags to 0
Ryan-rsm-McKenzie/CommonLibF4 pull request #9
Opened 2022-10-13 20:15 UTC by hxef

calloc appears to return random data instead of initializing the flag list with zeros. 

This results in inconsistent behavior when modifying the extra data list. Given that methods such as HasType or MarkType check these flags to verify if an extra data type is part of the list.

2022-10-13 20:18 UTC, Ryan-rsm-McKenzie requested changes

2022-10-13 20:18 UTC, Ryan-rsm-McKenzie commented on CommonLibF4/include/RE/Bethesda/BSExtraData.h
> +			memset(_flags, 0, N);
```suggestion
			std::memset(_flags, 0, N);
```
Please resolve all `std` namespaces

2022-10-13 20:32 UTC, hxef commented on CommonLibF4/include/RE/Bethesda/BSExtraData.h
> +			memset(_flags, 0, N);
Done.

2022-10-13 20:43 UTC, Ryan-rsm-McKenzie approved these changes

2022-10-13 20:43 UTC, merged

2022-10-13 20:43 UTC, Ryan-rsm-McKenzie commented
Thanks for the pr!

2022-10-14 21:34 UTC, clayne commented
BTW: Is [this](https://github.com/Ryan-rsm-McKenzie/CommonLibF4/blob/be124d1c5fd02b8b0eaf0c6f02869f49e1977be7/CommonLibF4/include/RE/Bethesda/MemoryManager.h#L292) the real issue? From MemoryManager.h (Same thing in `CommonLibSSE` btw):
```
        [[nodiscard]] inline void* calloc(std::size_t a_num, std::size_t a_size)
        {
                return malloc(a_num * a_size);
        }
```

2022-10-14 23:02 UTC, hxef commented
@clayne correct, I think the real fix should've been in the calloc function, something like this:
`    [[nodiscard]] inline void* calloc(std::size_t a_num, std::size_t a_size)
    {
        auto ret = malloc(a_num * a_size);
        memset(ret, 0, a_num * a_size);
        return ret;
    }
`

2022-10-15 00:05 UTC, hxef commented
@Ryan-rsm-McKenzie could you revert this PR? As per discord discussion in the fallout channel, I got a suggestion to create another one that handles it at the source of the problem, namely in the calloc() function.